{
 "title": "NEO-Custome-Outbox",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BE_CPU_TIME (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_time_seconds_total{state=\"user\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox - processors cycle processing time [ticks]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "event_bus_outbox_delivery_processor_status",
     "legendFormat": "__auto"
    },
    {
     "expr": "event_bus_outbox_monitoring_processor_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BE_MEM (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(process_memory_usage_bytes/1024/1024) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox-queue(hot/cold)-status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "event_bus_outbox_hot_table_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "event_bus_outbox_hot_message_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "event_bus_outbox_cold_message_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(process_runtime_dotnet_gc_heap_size_bytes/1024/1024) by(instance),\r\n  \"legend\", \"HEAP_SIZE_BYTES\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(process_runtime_dotnet_gc_heap_size_bytes{generation!=\"gen2\"}/1024/1024) by(instance),\r\n  \"legend\", \"Gen2_SIZE_BYTES\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(process_runtime_dotnet_gc_heap_size_bytes{generation=\"loh\"}/1024/1024) by(instance),\r\n  \"legend\", \"LOH_SIZE_BYTES\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(process_runtime_dotnet_gc_heap_fragmentation_size_bytes/1024/1024) by(instance),\r\n  \"legend\", \"FRAG_SIZE_BYTES\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  avg(rate(process_runtime_dotnet_gc_collections_count_total{generation=\"gen0\"}[1m])*60) by(instance),\r\n  \"legend\", \"Gen0-COLLECT/min\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  avg(rate(process_runtime_dotnet_gc_collections_count_total{generation=\"gen1\"}[1m])*60) by(instance),\r\n  \"legend\", \"Gen1-COLLECT/min\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  avg(rate(process_runtime_dotnet_gc_collections_count_total{generation=\"gen2\"}[1m])*60) by(instance),\r\n  \"legend\", \"Gen2-COLLECT/min\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox - enqueue/publish - success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(rate(event_bus_outbox_message_enqueued_succeed_total[1m])) by (job),\r\n  \"legend\", \"Enqueued messages/s\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(rate(event_bus_outbox_message_published_succeed_total[1m])) by (job),\r\n  \"legend\", \"Published messages/s\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(rate(neo_app_real_game_rounds_sec_total[1m])) by (job),\r\n  \"legend\", \"GRs/s\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GR/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(neo_app_real_game_rounds_sec_total[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(rate(neo_app_real_game_rounds_sec_total[$__rate_interval])),\r\n  \"instance\", \"Total\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox - enqueue/publish - failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "event_bus_outbox_message_enqueue_failed_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "event_bus_outbox_message_publish_failed_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(rate(event_bus_outbox_message_publish_failed_total[1m])) by (job),\r\n  \"legend\", \"Publish failed/s\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Grains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum(orleans_grains_total{type=\"Neo.MsOrleans.Grains.SingleSeatGame.SingleSeatGameActor,Neo.MsOrleans\"}),\r\n  \"legend\", \"Single Seat Game Actors\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  sum(orleans_grains_total{type=\"Neo.MsOrleans.Grains.Common.PlatformSessionActor,Neo.MsOrleans\"}),\r\n  \"legend\", \"Session actors\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "neo_app_ms_orleans_active_grains",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox - publish latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(event_bus_outbox_publish_latency_in_ms_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(event_bus_outbox_publish_latency_in_ms_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(event_bus_outbox_publish_latency_in_ms_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Masstransit total sent messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "messaging_masstransit_send_ea_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox - End-to-End latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(event_bus_outbox_end_to_end_latency_in_ms_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(event_bus_outbox_end_to_end_latency_in_ms_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(event_bus_outbox_end_to_end_latency_in_ms_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}